###
GET http://localhost:3001/posts
###
POST http://localhost:3001/login
content-type: application/json
BODY
{ "username": "matt" }
###
GET http://localhost:5002/recipes HTTP/1.1
content-type: application/json  

###
POST http://localhost:5002/recipes HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:5002/recipe-upsert HTTP/1.1
content-type: application/json

 {
    "id": 22,
    "servings": "15",
    "cookTime": "1:45",
    "instructions": "1. Put salt on chicken\n2. Put chicken in oven\n3. Eat chicken",
    "ingredients": [
      {
        "id": 1,
        "name": "Chicken",
        "amount": "2 Pounds"
      },
      {
        "id": 2,
        "name": "Salt",
        "amount": "1 Tbs"
      }
    ]
  }
###

POST http://localhost:5002/recipe-add HTTP/1.1
content-type: application/json

 {
    "id": "14",
    "servings": "4",
    "cookTime": "1:45",
    "name": "Gerneral Nunny's Chicken",
    "instructions": "1. Put salt on chicken\n2. Put chicken in oven\n3. Eat chicken",
    "ingredients": [
      {
        "id": 1,
        "name": "Chicken",
        "amount": "2 Pounds"
      },
      {
        "id": 2,
        "name": "Salt",
        "amount": "1 Tbs"
      }
    ]
  }
###
DELETE http://localhost:5002/recipe-delete HTTP/1.1
content-type: application/json

 {
    "id": "14"
  }
###

###
POST http://localhost:5002/api/v1/users/create HTTP/1.1
content-type: application/json

{ "username": "matt1",
  "password": "password1",
  "email": "matthew.raymond.wong@gmail.com1" 
}
###
DELETE http://localhost:5002/api/v1/users/delete HTTP/1.1
content-type: application/json

{
    "email": "1matthew.raymond.wong@gmail.com"
}
###

POST http://localhost:5002/api/v1/users/login HTTP/1.1
content-type: application/json

{ 
  "password": "$2b$10$md1pQfuaRXSvGrqh9CaF4uOoOJOj/Sj/POgiI.lejRu9CE41oSgqO",
  "email": "hello_molly@hotmail.com" 
}
### without authorization
GET http://localhost:5002/recipes HTTP/1.1
content-type: application/json  

###
GET http://localhost:5002/recipes HTTP/1.1
content-type: application/json  
# Cookie: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13b25ndGVzdDAyIiwiaWF0IjoxNTk3OTUzMjM3LCJleHAiOjE2MDAxMTMyMzd9.8lvdIyocnxsCkNSyyXwazrsthEeRQL4HsJvGw4MjavY
 
###

POST http://localhost:5002/api/v1/users/token HTTP/1.1
content-type: application/json

{ "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXdvbmd0ZXN0MDIiLCJpYXQiOjE1OTc4NDY0MjB9.Uwv3fME-jmIetU5Qw4XXyvM3MGl5n-6tBNKCDW1wxcE" }

###

DELETE http://localhost:5002/api/v1/users/logout HTTP/1.1
content-type: application/json

{ "username": "mwongtest02"}
###


POST http://localhost:5002/api/v1/users/verify-email HTTP/1.1
content-type: application/json

{ "username": "mwongtest02",
  "email": "matthew.raymond.wong@gmail.com",
  "message": "test msg"
}
###

POST http://localhost:5003/send-email-verification-code HTTP/1.1
content-type: application/json

{ "username": "mwongtest02",
  "email": "matthew.raymond.wong@gmail.com",
  "message": "test msg"
}
###
